# This removes the users 'adminuser' and 'cmsuser' from the machine defined by the 'hosts' variable.
# Variables are located in the file 'vagrant_variales.yml' file. Before running the script you must:
# 1) Have 'root' access to the server.
# 2) Be run before root acces is removed from SSH to the server.
#
# To run:
# />  ansible-playbook removeCMSandAdminAccountsWithRootUser.yml --ask-pass
#
# Use the root password of the server when prompted.


# This is a test script is to remove cms and admin users for a system as the root user.
# This script is just to clean up a failed deployment and can only be run before a root account is blocked from
# SSH access
---

- hosts: NoisyAtom-Portal
  user: '{{rootuser}}'
  become: true                                               # This will tell ansible to become 'sudo' to issue commands on the machine


  vars_files:
    - vars/vagrant_variables.yml

  vars:
    ansible_ssh_user: '{{rootuser}}'                         # become a root user
  tasks:

  - name: Remove user adminuser
    user:
      name: '{{ adminuser }}'
      state: absent
      remove: yes

  - name: Remove user cmsuser
    user:
      name: '{{ cmsuser }}'
      state: absent
      remove: yes

